[package]
name = "nmcr_parser"
version = "0.1.0"
edition = "2024"
description = "Markdown-to-templates parser for nmcr"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/nmcr"

[dependencies]
anyhow = "1.0.99"
# Using the `markdown` crate for mdast parsing
markdown = "1.0.0"
nmcr_types = { version = "0.1.0", path = "../types" }

[dev-dependencies]
insta = { version = "1.39.0", features = ["glob"] }
indoc = "2"
