[workspace]
resolver = "2"
members = [
  "pkgs/cli",
  "pkgs/mcp",
  "pkgs/md-parser",
  "pkgs/catalog",
  "pkgs/id",
  "pkgs/project",
  "pkgs/types-internal",
  "pkgs/types-rs",
  "pkgs/template",
]
