[package]
name = "nmcr_mcp"
version = "0.1.0"
edition = "2024"
description = "nmcr MCP crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/nmcr"

[dependencies]
anyhow = "1.0.99"
futures = "0.3.31"
nmcr_parser = { version = "0.1.0", path = "../parser" }
nmcr_project = { version = "0.1.0", path = "../project" }
nmcr_types = { version = "0.1.0", path = "../types" }
rmcp = { version = "0.6.4", features = ["transport-io"] }
serde_json = "1.0.132"

[dev-dependencies]
pretty_assertions = "1.4.0"

