[package]
name = "nmcr_template"
version = "0.0.0"
edition = "2024"
description = "Shared Handlebars renderer and helpers for nmcr"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/nmcr"

[dependencies]
anyhow = "1.0.99"
handlebars = "5.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.133"
