[package]
name = "nmcr_md_parser"
version = "0.0.0"
edition = "2024"
description = "Markdown-to-templates parser for nmcr"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/nmcr"

[dependencies]
anyhow = "1.0.99"
markdown = "1.0.0"
nmcr_types_internal = { version = "0.0.0", path = "../types-internal" }
nmcr_id = { version = "0.0.0", path = "../nmcr_id" }
relative-path = "1.9.3"

[dev-dependencies]
insta = { version = "1.39.0", features = ["glob"] }
indoc = "2"
