[package]
name = "nmcr"
version = "0.1.0"
edition = "2024"
description = "Agent-enabled scaffolding & code generation tool"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/nmcr"

[[bin]]
name = "nmcr"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
config = "0.15.15"
dialoguer = "0.12.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.8.19", features = ["parse", "display"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
console = "0.16.0"
indicatif = { version = "0.18.0", features = ["tokio"] }
nmcr_project = { version = "0.1.0", path = "../project" }
nmcr_parser = { version = "0.1.0", path = "../parser" }
