[package]
name = "nmcr_catalog"
version = "0.0.0"
edition = "2024"
description = "Shared template catalog loader for nmcr"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/nmcr"

[dependencies]
anyhow = "1.0.99"
nmcr_md_parser = { version = "0.0.0", path = "../md-parser" }
nmcr_types = { version = "0.1.0", path = "../types-rs" }
nmcr_types_internal = { version = "0.0.0", path = "../types-internal" }
