[package]
name = "nmcr_types"
version = "0.1.0"
edition = "2024"
description = "Types for nmcr templates and collections"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/nmcr"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
